### PR TITLE
Replace README header

### PR DESCRIPTION
**Pull request by anabangueses**
### Short description

Update README to replace header image. Change url from `.in` to `.io`

### CODE REVIEW

**Review by sergigracia — APPROVED** [review]
🎉

**Comment by pepicrft** [comment]
---

## When my colleague messages me bad puns

alt text

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">danger</a>
</p>

**Comment by pepicrft** [comment]
Lol! well done @anabangueses

**Comment by pepicrft** [comment]
👍

**Pull request merged**
